### PR TITLE
Fix finding libsodium.so with ruby 2.5

### LINKED ISSUE #25: Fails to build with ruby 2.5?
Hi,

Not sure if it's strictly ruby 2.5 related but I started experiencing issues at the time I updated it.

```
TypeError: no implicit conversion of nil into String
.bundle/gems/rbnacl-libsodium-1.0.16/lib/rbnacl/libsodium.rb:23:in `join'
.bundle/gems/rbnacl-libsodium-1.0.16/lib/rbnacl/libsodium.rb:23:in `<module:Libsodium>'
.bundle/gems/rbnacl-libsodium-1.0.16/lib/rbnacl/libsodium.rb:4:in `<module:RbNaCl>'
.bundle/gems/rbnacl-libsodium-1.0.16/lib/rbnacl/libsodium.rb:3:in `<top (required)>'
.bundle/gems/macaroons-1.0.0/lib/macaroons/raw_macaroon.rb:3:in `require'
.bundle/gems/macaroons-1.0.0/lib/macaroons/raw_macaroon.rb:3:in `<top (required)>'
.bundle/gems/macaroons-1.0.0/lib/macaroons/macaroons.rb:3:in `require'
.bundle/gems/macaroons-1.0.0/lib/macaroons/macaroons.rb:3:in `<top (required)>'
.bundle/gems/macaroons-1.0.0/lib/macaroons.rb:1:in `require'
.bundle/gems/macaroons-1.0.0/lib/macaroons.rb:1:in `<top (required)>'
```

### PR DESCRIPTION
**Pull request by Keruspe**
Fixes #25

### CODE REVIEW

**Comment by Keruspe** [comment]
I'm not sure if it's the right path to look into. It's both in `vendor/libsodium/src/libsodium/.libs/libsodium.so` and `tmp/x86_64-linux/stage/vendor/libsodium/dist/lib/libsodium.so`. Former seemed simpler.

**Comment by Keruspe** [comment]
I actually understood what's going on there and made a more complete and proper fix:

For some reasons, starting with ruby 2.5, HOST ends up being defined in extconf.rb, thus DIST ends up with a different value. I adjusted the check here to look into the two different DIST possibilities when we used to look inside of only one of those.

**Comment by tarcieri** [comment]
there are some ongoing issues with that code. see #24

**Comment by Keruspe** [comment]
@tarcieri right, thanks for the notice. doesn't seem to be the same error though, do you think it could be related?

This PR basically fixes the fact that extconf.rb could install the so in two different locations but rbnacl/libsodium.rb was only looking into one of those two locations

**Comment by tarcieri** [comment]
Thanks!

**Pull request merged**
